### ISSUE TITLE
reward function

### ISSUE THREAD

**Issue by sparkzzl** [JasonCaldwellMBA/AWS_DeepRacer-Object_Avoidance#1]
I want to study your reward function in objects avoidance, can you share it

**Comment by JasonCaldwellMBA** [comment]
The different reward functions are available throughout the project. One example is at https://github.com/JasonCaldwellMBA/AWS_DeepRacer-Object_Avoidance/blob/main/Object_Avoidance_v4_Clone_Time-Trial-v5.md#reward-function.
